//! External type definitions loader.
//!
//! Loads type information from JSON files generated by the tsc type extraction script.
//! Converts the TypeScript-centric JSON representation into [`TypeDef`] entries
//! and registers them in a [`TypeRegistry`].

use std::collections::HashMap;

use anyhow::{bail, Context, Result};
use serde::Deserialize;

use crate::ir::RustType;
use crate::pipeline::SyntheticTypeRegistry;
use crate::registry::{MethodSignature, TypeDef, TypeRegistry};

/// JSON interchange format version. Must match the tsc extraction script's output.
const FORMAT_VERSION: u64 = 2;

// ── JSON schema types ──────────────────────────────────────────────

/// Top-level JSON structure produced by the tsc type extraction script.
#[derive(Debug, Deserialize)]
pub struct ExternalTypesJson {
    /// Format version for compatibility checking.
    pub version: u64,
    /// Map of type name → type definition.
    pub types: HashMap<String, ExternalTypeDef>,
}

/// A type parameter in an external type definition.
#[derive(Debug, Deserialize)]
pub struct ExternalTypeParam {
    pub name: String,
    #[serde(default)]
    pub constraint: Option<ExternalType>,
}

/// A single type definition in the JSON interchange format.
#[derive(Debug, Deserialize)]
#[serde(tag = "kind")]
pub enum ExternalTypeDef {
    /// An interface or object type.
    #[serde(rename = "interface")]
    Interface {
        #[serde(default)]
        type_params: Vec<ExternalTypeParam>,
        #[serde(default)]
        fields: Vec<ExternalField>,
        #[serde(default)]
        methods: HashMap<String, ExternalMethod>,
        #[serde(default)]
        constructors: Vec<ExternalSignature>,
    },
    /// A function declaration.
    #[serde(rename = "function")]
    Function { signatures: Vec<ExternalSignature> },
    /// A type alias (resolved to its underlying representation).
    #[serde(rename = "alias")]
    Alias {
        #[serde(rename = "type")]
        resolved_type: ExternalType,
    },
}

/// A field in an interface.
#[derive(Debug, Deserialize)]
pub struct ExternalField {
    pub name: String,
    #[serde(rename = "type")]
    pub field_type: ExternalType,
    #[serde(default)]
    pub optional: bool,
    #[serde(default)]
    pub readonly: bool,
}

/// A method with possibly multiple overload signatures.
#[derive(Debug, Deserialize)]
pub struct ExternalMethod {
    pub signatures: Vec<ExternalSignature>,
}

/// A function/method/constructor signature.
#[derive(Debug, Deserialize)]
pub struct ExternalSignature {
    #[serde(default)]
    pub params: Vec<ExternalParam>,
    #[serde(default)]
    pub return_type: Option<ExternalType>,
}

/// A parameter in a signature.
#[derive(Debug, Deserialize)]
pub struct ExternalParam {
    pub name: String,
    #[serde(rename = "type")]
    pub param_type: ExternalType,
    #[serde(default)]
    pub optional: bool,
    #[serde(default)]
    pub rest: bool,
}

/// TypeScript type representation in the JSON interchange format.
#[derive(Debug, Deserialize)]
#[serde(tag = "kind")]
pub enum ExternalType {
    #[serde(rename = "string")]
    String,
    #[serde(rename = "number")]
    Number,
    #[serde(rename = "boolean")]
    Boolean,
    #[serde(rename = "void")]
    Void,
    #[serde(rename = "any")]
    Any,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "never")]
    Never,
    #[serde(rename = "null")]
    Null,
    #[serde(rename = "undefined")]
    Undefined,
    #[serde(rename = "named")]
    Named {
        name: String,
        #[serde(default)]
        type_args: Vec<ExternalType>,
    },
    #[serde(rename = "array")]
    Array { element: Box<ExternalType> },
    #[serde(rename = "tuple")]
    Tuple { elements: Vec<ExternalType> },
    #[serde(rename = "union")]
    Union { members: Vec<ExternalType> },
    #[serde(rename = "function")]
    Function {
        #[serde(default)]
        params: Vec<ExternalType>,
        return_type: Box<ExternalType>,
    },
}

// ── Built-in types ─────────────────────────────────────────────────

/// Pre-generated Web API type definitions (Response, Request, Headers, etc.)
/// extracted from lib.dom.d.ts using the tsc type extraction script.
const WEB_API_TYPES_JSON: &str = include_str!("../builtin_types/web_api.json");

/// Pre-generated ECMAScript standard type definitions (String, Array, Date, etc.)
/// extracted from lib.es5.d.ts and lib.es2015.*.d.ts using the tsc type extraction script.
const ECMASCRIPT_TYPES_JSON: &str = include_str!("../builtin_types/ecmascript.json");

/// Loads the built-in type definitions into a [`TypeRegistry`].
///
/// Loads ECMAScript standard types first, then Web API types. Types defined in
/// both (e.g., `Promise`) use the Web API version, which includes DOM-specific
/// declaration merging extensions.
///
/// # Errors
///
/// Returns an error if the embedded JSON is malformed (should not happen
/// in a correctly built binary).
pub fn load_builtin_types() -> Result<(TypeRegistry, SyntheticTypeRegistry)> {
    let mut registry = TypeRegistry::new();
    let mut synthetic = SyntheticTypeRegistry::new();
    load_types_into(&mut registry, &mut synthetic, ECMASCRIPT_TYPES_JSON)?;
    load_types_into(&mut registry, &mut synthetic, WEB_API_TYPES_JSON)?;
    Ok((registry, synthetic))
}

// ── Conversion logic ───────────────────────────────────────────────

/// Loads external type definitions from a JSON string.
///
/// Returns both a [`TypeRegistry`] and a [`SyntheticTypeRegistry`] containing
/// synthetic enums generated from multi-member union types.
///
/// # Errors
///
/// Returns an error if JSON is malformed or the format version is unsupported.
pub fn load_types_json(json: &str) -> Result<(TypeRegistry, SyntheticTypeRegistry)> {
    let mut registry = TypeRegistry::new();
    let mut synthetic = SyntheticTypeRegistry::new();
    load_types_into(&mut registry, &mut synthetic, json)?;
    Ok((registry, synthetic))
}

/// Loads external type definitions from a JSON string into an existing
/// [`TypeRegistry`] and [`SyntheticTypeRegistry`].
///
/// Types are added via [`TypeRegistry::register`] (`HashMap::insert`),
/// so later calls overwrite earlier entries with the same name.
///
/// # Errors
///
/// Returns an error if JSON is malformed or the format version is unsupported.
pub fn load_types_into(
    registry: &mut TypeRegistry,
    synthetic: &mut SyntheticTypeRegistry,
    json: &str,
) -> Result<()> {
    let parsed: ExternalTypesJson =
        serde_json::from_str(json).context("failed to parse external types JSON")?;
    if parsed.version != FORMAT_VERSION {
        bail!(
            "unsupported external types format version: {} (expected {})",
            parsed.version,
            FORMAT_VERSION
        );
    }
    for (name, def) in parsed.types {
        if let Some(type_def) = convert_external_typedef(&def, synthetic) {
            registry.register_external(name.clone(), type_def);
        }
    }
    Ok(())
}

/// Converts an [`ExternalTypeDef`] to a [`TypeDef`].
fn convert_external_typedef(
    def: &ExternalTypeDef,
    synthetic: &mut SyntheticTypeRegistry,
) -> Option<TypeDef> {
    match def {
        ExternalTypeDef::Interface {
            type_params,
            fields,
            methods,
            constructors,
        } => {
            let converted_type_params: Vec<crate::ir::TypeParam> = type_params
                .iter()
                .map(|tp| crate::ir::TypeParam {
                    name: tp.name.clone(),
                    constraint: tp
                        .constraint
                        .as_ref()
                        .map(|c| convert_external_type(c, synthetic)),
                })
                .collect();

            let converted_fields: Vec<(String, RustType)> = fields
                .iter()
                .map(|f| {
                    let ty = convert_external_type(&f.field_type, synthetic);
                    let ty = if f.optional {
                        RustType::Option(Box::new(ty))
                    } else {
                        ty
                    };
                    (f.name.clone(), ty)
                })
                .collect();

            let converted_methods: HashMap<String, Vec<MethodSignature>> = methods
                .iter()
                .filter_map(|(name, method)| {
                    let sigs: Vec<MethodSignature> = method
                        .signatures
                        .iter()
                        .map(|sig| convert_external_signature(sig, synthetic))
                        .collect();
                    if sigs.is_empty() {
                        None
                    } else {
                        Some((name.clone(), sigs))
                    }
                })
                .collect();

            let converted_constructors: Option<Vec<MethodSignature>> = {
                let sigs: Vec<MethodSignature> = constructors
                    .iter()
                    .map(|sig| convert_external_signature(sig, synthetic))
                    .collect();
                if sigs.is_empty() {
                    None
                } else {
                    Some(sigs)
                }
            };

            Some(TypeDef::Struct {
                type_params: converted_type_params,
                fields: converted_fields,
                methods: converted_methods,
                constructor: converted_constructors,
                extends: vec![],
                is_interface: true,
            })
        }
        ExternalTypeDef::Function { signatures } => {
            let sig = signatures.first()?;
            let params = convert_external_params(&sig.params, synthetic);
            let return_type = sig
                .return_type
                .as_ref()
                .map(|rt| convert_external_type(rt, synthetic));
            let has_rest = sig.params.last().is_some_and(|p| p.rest);
            Some(TypeDef::Function {
                params,
                return_type,
                has_rest,
            })
        }
        ExternalTypeDef::Alias { resolved_type } => {
            // Type aliases are resolved by tsc; store the resolved form.
            // If it resolves to a named type, we don't need a registry entry
            // (it will be referenced by name). Return None for now.
            match resolved_type {
                ExternalType::Named { .. } => None,
                _ => None, // TODO: handle more alias patterns as needed
            }
        }
    }
}

/// Converts an [`ExternalType`] to a [`RustType`].
fn convert_external_type(ty: &ExternalType, synthetic: &mut SyntheticTypeRegistry) -> RustType {
    match ty {
        ExternalType::String => RustType::String,
        ExternalType::Number => RustType::F64,
        ExternalType::Boolean => RustType::Bool,
        ExternalType::Void => RustType::Unit,
        ExternalType::Any | ExternalType::Unknown => RustType::Any,
        ExternalType::Never => RustType::Never,
        ExternalType::Null | ExternalType::Undefined => RustType::Option(Box::new(RustType::Any)),
        ExternalType::Named { name, type_args } => RustType::Named {
            name: name.clone(),
            type_args: type_args
                .iter()
                .map(|t| convert_external_type(t, synthetic))
                .collect(),
        },
        ExternalType::Array { element } => {
            RustType::Vec(Box::new(convert_external_type(element, synthetic)))
        }
        ExternalType::Tuple { elements } => RustType::Tuple(
            elements
                .iter()
                .map(|t| convert_external_type(t, synthetic))
                .collect(),
        ),
        ExternalType::Union { members } => convert_union_type(members, synthetic),
        ExternalType::Function {
            params,
            return_type,
        } => RustType::Fn {
            params: params
                .iter()
                .map(|t| convert_external_type(t, synthetic))
                .collect(),
            return_type: Box::new(convert_external_type(return_type, synthetic)),
        },
    }
}

/// Converts a union type, handling the `T | null` → `Option<T>` pattern.
///
/// Multi-member non-nullable unions are converted to synthetic enums via
/// [`SyntheticTypeRegistry::register_union`].
fn convert_union_type(members: &[ExternalType], synthetic: &mut SyntheticTypeRegistry) -> RustType {
    let mut non_null: Vec<&ExternalType> = Vec::new();
    let mut has_null = false;

    for m in members {
        match m {
            ExternalType::Null | ExternalType::Undefined => has_null = true,
            _ => non_null.push(m),
        }
    }

    let inner = if non_null.len() == 1 {
        convert_external_type(non_null[0], synthetic)
    } else if non_null.is_empty() {
        RustType::Any
    } else {
        let member_types: Vec<RustType> = non_null
            .iter()
            .map(|m| convert_external_type(m, synthetic))
            .collect();
        let enum_name = synthetic.register_union(&member_types);
        RustType::Named {
            name: enum_name,
            type_args: vec![],
        }
    };

    if has_null {
        RustType::Option(Box::new(inner))
    } else {
        inner
    }
}

/// Converts external parameters to `(name, RustType)` pairs.
///
/// Handles optional parameters by wrapping their types in `Option<T>`.
fn convert_external_params(
    params: &[ExternalParam],
    synthetic: &mut SyntheticTypeRegistry,
) -> Vec<(String, RustType)> {
    params
        .iter()
        .map(|p| {
            let ty = convert_external_type(&p.param_type, synthetic);
            let ty = if p.optional {
                RustType::Option(Box::new(ty))
            } else {
                ty
            };
            (p.name.clone(), ty)
        })
        .collect()
}

/// Converts an [`ExternalSignature`] to a [`MethodSignature`].
fn convert_external_signature(
    sig: &ExternalSignature,
    synthetic: &mut SyntheticTypeRegistry,
) -> MethodSignature {
    let params = convert_external_params(&sig.params, synthetic);
    let return_type = sig
        .return_type
        .as_ref()
        .map(|rt| convert_external_type(rt, synthetic));
    MethodSignature {
        params,
        return_type,
    }
}

#[cfg(test)]
mod tests;
