//! External type definitions loader.
//!
//! Loads type information from JSON files generated by the tsc type extraction script.
//! Converts the TypeScript-centric JSON representation into [`TypeDef`] entries
//! and registers them in a [`TypeRegistry`].

use std::collections::HashMap;

use anyhow::{bail, Context, Result};
use serde::Deserialize;

use crate::ir::RustType;
use crate::registry::{TypeDef, TypeRegistry};

/// JSON interchange format version. Must match the tsc extraction script's output.
const FORMAT_VERSION: u64 = 1;

// ── JSON schema types ──────────────────────────────────────────────

/// Top-level JSON structure produced by the tsc type extraction script.
#[derive(Debug, Deserialize)]
pub struct ExternalTypesJson {
    /// Format version for compatibility checking.
    pub version: u64,
    /// Map of type name → type definition.
    pub types: HashMap<String, ExternalTypeDef>,
}

/// A single type definition in the JSON interchange format.
#[derive(Debug, Deserialize)]
#[serde(tag = "kind")]
pub enum ExternalTypeDef {
    /// An interface or object type.
    #[serde(rename = "interface")]
    Interface {
        #[serde(default)]
        fields: Vec<ExternalField>,
        #[serde(default)]
        methods: HashMap<String, ExternalMethod>,
        #[serde(default)]
        constructors: Vec<ExternalSignature>,
    },
    /// A function declaration.
    #[serde(rename = "function")]
    Function { signatures: Vec<ExternalSignature> },
    /// A type alias (resolved to its underlying representation).
    #[serde(rename = "alias")]
    Alias {
        #[serde(rename = "type")]
        resolved_type: ExternalType,
    },
}

/// A field in an interface.
#[derive(Debug, Deserialize)]
pub struct ExternalField {
    pub name: String,
    #[serde(rename = "type")]
    pub field_type: ExternalType,
    #[serde(default)]
    pub optional: bool,
    #[serde(default)]
    pub readonly: bool,
}

/// A method with possibly multiple overload signatures.
#[derive(Debug, Deserialize)]
pub struct ExternalMethod {
    pub signatures: Vec<ExternalSignature>,
}

/// A function/method/constructor signature.
#[derive(Debug, Deserialize)]
pub struct ExternalSignature {
    #[serde(default)]
    pub params: Vec<ExternalParam>,
    #[serde(default)]
    pub return_type: Option<ExternalType>,
}

/// A parameter in a signature.
#[derive(Debug, Deserialize)]
pub struct ExternalParam {
    pub name: String,
    #[serde(rename = "type")]
    pub param_type: ExternalType,
    #[serde(default)]
    pub optional: bool,
    #[serde(default)]
    pub rest: bool,
}

/// TypeScript type representation in the JSON interchange format.
#[derive(Debug, Deserialize)]
#[serde(tag = "kind")]
pub enum ExternalType {
    #[serde(rename = "string")]
    String,
    #[serde(rename = "number")]
    Number,
    #[serde(rename = "boolean")]
    Boolean,
    #[serde(rename = "void")]
    Void,
    #[serde(rename = "any")]
    Any,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "never")]
    Never,
    #[serde(rename = "null")]
    Null,
    #[serde(rename = "undefined")]
    Undefined,
    #[serde(rename = "named")]
    Named {
        name: String,
        #[serde(default)]
        type_args: Vec<ExternalType>,
    },
    #[serde(rename = "array")]
    Array { element: Box<ExternalType> },
    #[serde(rename = "tuple")]
    Tuple { elements: Vec<ExternalType> },
    #[serde(rename = "union")]
    Union { members: Vec<ExternalType> },
    #[serde(rename = "function")]
    Function {
        #[serde(default)]
        params: Vec<ExternalType>,
        return_type: Box<ExternalType>,
    },
}

// ── Built-in types ─────────────────────────────────────────────────

/// Pre-generated Web API type definitions (Response, Request, Headers, etc.)
/// extracted from lib.dom.d.ts using the tsc type extraction script.
const BUILTIN_TYPES_JSON: &str = include_str!("builtin_types.json");

/// Loads the built-in Web API type definitions into a [`TypeRegistry`].
///
/// These types are pre-generated from TypeScript's lib.dom.d.ts using the
/// tsc Compiler API, ensuring full inheritance resolution (e.g., Response
/// includes Body's methods like json() and text()).
///
/// # Errors
///
/// Returns an error if the embedded JSON is malformed (should not happen
/// in a correctly built binary).
pub fn load_builtin_types() -> Result<TypeRegistry> {
    load_types_json(BUILTIN_TYPES_JSON)
}

// ── Conversion logic ───────────────────────────────────────────────

/// Loads external type definitions from a JSON string and returns a [`TypeRegistry`].
///
/// # Errors
///
/// Returns an error if JSON is malformed or the format version is unsupported.
pub fn load_types_json(json: &str) -> Result<TypeRegistry> {
    let parsed: ExternalTypesJson =
        serde_json::from_str(json).context("failed to parse external types JSON")?;
    if parsed.version != FORMAT_VERSION {
        bail!(
            "unsupported external types format version: {} (expected {})",
            parsed.version,
            FORMAT_VERSION
        );
    }
    let mut registry = TypeRegistry::new();
    for (name, def) in parsed.types {
        if let Some(type_def) = convert_external_typedef(&def) {
            registry.register(name.clone(), type_def);
        }
    }
    Ok(registry)
}

/// Converts an [`ExternalTypeDef`] to a [`TypeDef`].
fn convert_external_typedef(def: &ExternalTypeDef) -> Option<TypeDef> {
    match def {
        ExternalTypeDef::Interface {
            fields,
            methods,
            constructors: _,
        } => {
            let converted_fields: Vec<(String, RustType)> = fields
                .iter()
                .map(|f| {
                    let ty = convert_external_type(&f.field_type);
                    let ty = if f.optional {
                        RustType::Option(Box::new(ty))
                    } else {
                        ty
                    };
                    (f.name.clone(), ty)
                })
                .collect();

            let converted_methods: HashMap<String, Vec<(String, RustType)>> = methods
                .iter()
                .filter_map(|(name, method)| {
                    // Use the first signature (most general for overloads)
                    let sig = method.signatures.first()?;
                    let params = sig
                        .params
                        .iter()
                        .map(|p| {
                            let ty = convert_external_type(&p.param_type);
                            let ty = if p.optional {
                                RustType::Option(Box::new(ty))
                            } else {
                                ty
                            };
                            (p.name.clone(), ty)
                        })
                        .collect();
                    Some((name.clone(), params))
                })
                .collect();

            Some(TypeDef::Struct {
                fields: converted_fields,
                methods: converted_methods,
            })
        }
        ExternalTypeDef::Function { signatures } => {
            let sig = signatures.first()?;
            let params = sig
                .params
                .iter()
                .map(|p| {
                    let ty = convert_external_type(&p.param_type);
                    let ty = if p.optional {
                        RustType::Option(Box::new(ty))
                    } else {
                        ty
                    };
                    (p.name.clone(), ty)
                })
                .collect();
            let return_type = sig.return_type.as_ref().map(convert_external_type);
            let has_rest = sig.params.last().is_some_and(|p| p.rest);
            Some(TypeDef::Function {
                params,
                return_type,
                has_rest,
            })
        }
        ExternalTypeDef::Alias { resolved_type } => {
            // Type aliases are resolved by tsc; store the resolved form.
            // If it resolves to a named type, we don't need a registry entry
            // (it will be referenced by name). Return None for now.
            match resolved_type {
                ExternalType::Named { .. } => None,
                _ => None, // TODO: handle more alias patterns as needed
            }
        }
    }
}

/// Converts an [`ExternalType`] to a [`RustType`].
fn convert_external_type(ty: &ExternalType) -> RustType {
    match ty {
        ExternalType::String => RustType::String,
        ExternalType::Number => RustType::F64,
        ExternalType::Boolean => RustType::Bool,
        ExternalType::Void => RustType::Unit,
        ExternalType::Any | ExternalType::Unknown => RustType::Any,
        ExternalType::Never => RustType::Never,
        ExternalType::Null | ExternalType::Undefined => RustType::Option(Box::new(RustType::Any)),
        ExternalType::Named { name, type_args } => RustType::Named {
            name: name.clone(),
            type_args: type_args.iter().map(convert_external_type).collect(),
        },
        ExternalType::Array { element } => RustType::Vec(Box::new(convert_external_type(element))),
        ExternalType::Tuple { elements } => {
            RustType::Tuple(elements.iter().map(convert_external_type).collect())
        }
        ExternalType::Union { members } => convert_union_type(members),
        ExternalType::Function {
            params,
            return_type,
        } => RustType::Fn {
            params: params.iter().map(convert_external_type).collect(),
            return_type: Box::new(convert_external_type(return_type)),
        },
    }
}

/// Converts a union type, handling the `T | null` → `Option<T>` pattern.
fn convert_union_type(members: &[ExternalType]) -> RustType {
    let mut non_null: Vec<&ExternalType> = Vec::new();
    let mut has_null = false;

    for m in members {
        match m {
            ExternalType::Null | ExternalType::Undefined => has_null = true,
            _ => non_null.push(m),
        }
    }

    let inner = if non_null.len() == 1 {
        convert_external_type(non_null[0])
    } else if non_null.is_empty() {
        RustType::Any
    } else {
        // Non-nullable union with multiple members — use the first member as a fallback.
        // A proper union → enum conversion would need more context.
        convert_external_type(non_null[0])
    };

    if has_null {
        RustType::Option(Box::new(inner))
    } else {
        inner
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── Primitive type parsing ─────────────────────────────────────

    #[test]
    fn test_parse_type_string_returns_rust_string() {
        let ty: ExternalType = serde_json::from_str(r#"{"kind":"string"}"#).unwrap();
        assert_eq!(convert_external_type(&ty), RustType::String);
    }

    #[test]
    fn test_parse_type_number_returns_f64() {
        let ty: ExternalType = serde_json::from_str(r#"{"kind":"number"}"#).unwrap();
        assert_eq!(convert_external_type(&ty), RustType::F64);
    }

    #[test]
    fn test_parse_type_boolean_returns_bool() {
        let ty: ExternalType = serde_json::from_str(r#"{"kind":"boolean"}"#).unwrap();
        assert_eq!(convert_external_type(&ty), RustType::Bool);
    }

    #[test]
    fn test_parse_type_void_returns_unit() {
        let ty: ExternalType = serde_json::from_str(r#"{"kind":"void"}"#).unwrap();
        assert_eq!(convert_external_type(&ty), RustType::Unit);
    }

    #[test]
    fn test_parse_type_any_returns_any() {
        let ty: ExternalType = serde_json::from_str(r#"{"kind":"any"}"#).unwrap();
        assert_eq!(convert_external_type(&ty), RustType::Any);
    }

    #[test]
    fn test_parse_type_unknown_returns_any() {
        let ty: ExternalType = serde_json::from_str(r#"{"kind":"unknown"}"#).unwrap();
        assert_eq!(convert_external_type(&ty), RustType::Any);
    }

    #[test]
    fn test_parse_type_never_returns_never() {
        let ty: ExternalType = serde_json::from_str(r#"{"kind":"never"}"#).unwrap();
        assert_eq!(convert_external_type(&ty), RustType::Never);
    }

    // ── Composite type parsing ─────────────────────────────────────

    #[test]
    fn test_parse_type_nullable_returns_option() {
        let ty: ExternalType = serde_json::from_str(
            r#"{"kind":"union","members":[{"kind":"string"},{"kind":"null"}]}"#,
        )
        .unwrap();
        assert_eq!(
            convert_external_type(&ty),
            RustType::Option(Box::new(RustType::String))
        );
    }

    #[test]
    fn test_parse_type_array_returns_vec() {
        let ty: ExternalType =
            serde_json::from_str(r#"{"kind":"array","element":{"kind":"number"}}"#).unwrap();
        assert_eq!(
            convert_external_type(&ty),
            RustType::Vec(Box::new(RustType::F64))
        );
    }

    #[test]
    fn test_parse_type_tuple_returns_tuple() {
        let ty: ExternalType = serde_json::from_str(
            r#"{"kind":"tuple","elements":[{"kind":"string"},{"kind":"number"}]}"#,
        )
        .unwrap();
        assert_eq!(
            convert_external_type(&ty),
            RustType::Tuple(vec![RustType::String, RustType::F64])
        );
    }

    #[test]
    fn test_parse_type_named_returns_named() {
        let ty: ExternalType =
            serde_json::from_str(r#"{"kind":"named","name":"Response"}"#).unwrap();
        assert_eq!(
            convert_external_type(&ty),
            RustType::Named {
                name: "Response".to_string(),
                type_args: vec![],
            }
        );
    }

    #[test]
    fn test_parse_type_named_with_type_args() {
        let ty: ExternalType = serde_json::from_str(
            r#"{"kind":"named","name":"Promise","type_args":[{"kind":"any"}]}"#,
        )
        .unwrap();
        assert_eq!(
            convert_external_type(&ty),
            RustType::Named {
                name: "Promise".to_string(),
                type_args: vec![RustType::Any],
            }
        );
    }

    #[test]
    fn test_parse_type_function_returns_fn() {
        let ty: ExternalType = serde_json::from_str(
            r#"{"kind":"function","params":[{"kind":"string"}],"return_type":{"kind":"number"}}"#,
        )
        .unwrap();
        assert_eq!(
            convert_external_type(&ty),
            RustType::Fn {
                params: vec![RustType::String],
                return_type: Box::new(RustType::F64),
            }
        );
    }

    // ── Interface → TypeDef::Struct ────────────────────────────────

    #[test]
    fn test_parse_interface_returns_struct_typedef() {
        let json = r#"{
            "kind": "interface",
            "fields": [
                {"name": "status", "type": {"kind": "number"}, "readonly": true},
                {"name": "ok", "type": {"kind": "boolean"}, "readonly": true}
            ],
            "methods": {
                "clone": {
                    "signatures": [
                        {"params": [], "return_type": {"kind": "named", "name": "Response"}}
                    ]
                }
            }
        }"#;
        let def: ExternalTypeDef = serde_json::from_str(json).unwrap();
        let type_def = convert_external_typedef(&def).unwrap();
        match type_def {
            TypeDef::Struct { fields, methods } => {
                assert_eq!(fields.len(), 2);
                assert_eq!(fields[0].0, "status");
                assert_eq!(fields[0].1, RustType::F64);
                assert_eq!(fields[1].0, "ok");
                assert_eq!(fields[1].1, RustType::Bool);
                assert!(methods.contains_key("clone"));
            }
            _ => panic!("expected Struct, got {type_def:?}"),
        }
    }

    #[test]
    fn test_parse_interface_with_inherited_methods() {
        // tsc resolves inheritance, so Body's methods appear directly on Response
        let json = r#"{
            "kind": "interface",
            "fields": [
                {"name": "status", "type": {"kind": "number"}}
            ],
            "methods": {
                "json": {
                    "signatures": [
                        {"params": [], "return_type": {"kind": "named", "name": "Promise", "type_args": [{"kind": "any"}]}}
                    ]
                },
                "text": {
                    "signatures": [
                        {"params": [], "return_type": {"kind": "named", "name": "Promise", "type_args": [{"kind": "string"}]}}
                    ]
                }
            }
        }"#;
        let def: ExternalTypeDef = serde_json::from_str(json).unwrap();
        let type_def = convert_external_typedef(&def).unwrap();
        match type_def {
            TypeDef::Struct { methods, .. } => {
                assert!(methods.contains_key("json"), "should have inherited json()");
                assert!(methods.contains_key("text"), "should have inherited text()");
            }
            _ => panic!("expected Struct"),
        }
    }

    #[test]
    fn test_parse_interface_optional_field_becomes_option() {
        let json = r#"{
            "kind": "interface",
            "fields": [
                {"name": "status", "type": {"kind": "number"}, "optional": true}
            ],
            "methods": {}
        }"#;
        let def: ExternalTypeDef = serde_json::from_str(json).unwrap();
        let type_def = convert_external_typedef(&def).unwrap();
        match type_def {
            TypeDef::Struct { fields, .. } => {
                assert_eq!(fields[0].1, RustType::Option(Box::new(RustType::F64)));
            }
            _ => panic!("expected Struct"),
        }
    }

    // ── Function → TypeDef::Function ───────────────────────────────

    #[test]
    fn test_parse_function_returns_function_typedef() {
        let json = r#"{
            "kind": "function",
            "signatures": [
                {
                    "params": [
                        {"name": "input", "type": {"kind": "string"}},
                        {"name": "init", "type": {"kind": "named", "name": "RequestInit"}, "optional": true}
                    ],
                    "return_type": {"kind": "named", "name": "Promise", "type_args": [{"kind": "named", "name": "Response"}]}
                }
            ]
        }"#;
        let def: ExternalTypeDef = serde_json::from_str(json).unwrap();
        let type_def = convert_external_typedef(&def).unwrap();
        match type_def {
            TypeDef::Function {
                params,
                return_type,
                has_rest,
            } => {
                assert_eq!(params.len(), 2);
                assert_eq!(params[0].0, "input");
                assert_eq!(params[0].1, RustType::String);
                assert_eq!(params[1].0, "init");
                assert_eq!(
                    params[1].1,
                    RustType::Option(Box::new(RustType::Named {
                        name: "RequestInit".to_string(),
                        type_args: vec![],
                    }))
                );
                assert!(return_type.is_some());
                assert!(!has_rest);
            }
            _ => panic!("expected Function"),
        }
    }

    // ── load_types_json ────────────────────────────────────────────

    #[test]
    fn test_load_types_json_registers_all_types() {
        let json = r#"{
            "version": 1,
            "types": {
                "Response": {
                    "kind": "interface",
                    "fields": [{"name": "status", "type": {"kind": "number"}}],
                    "methods": {}
                },
                "Headers": {
                    "kind": "interface",
                    "fields": [],
                    "methods": {
                        "get": {
                            "signatures": [
                                {"params": [{"name": "name", "type": {"kind": "string"}}], "return_type": {"kind": "union", "members": [{"kind": "string"}, {"kind": "null"}]}}
                            ]
                        }
                    }
                }
            }
        }"#;
        let registry = load_types_json(json).unwrap();
        assert!(registry.get("Response").is_some());
        assert!(registry.get("Headers").is_some());
    }

    #[test]
    fn test_load_types_json_invalid_json_returns_error() {
        let result = load_types_json("{not valid json}");
        assert!(result.is_err());
    }

    #[test]
    fn test_load_types_json_version_mismatch_returns_error() {
        let json = r#"{"version": 99, "types": {}}"#;
        let result = load_types_json(json);
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("version"),
            "error should mention version: {err}"
        );
    }

    #[test]
    fn test_merge_external_types_local_takes_precedence() {
        let external_json = r#"{
            "version": 1,
            "types": {
                "Foo": {
                    "kind": "interface",
                    "fields": [{"name": "external_field", "type": {"kind": "string"}}],
                    "methods": {}
                }
            }
        }"#;
        let external_reg = load_types_json(external_json).unwrap();

        // Simulate local file defining Foo differently
        let local_source = "interface Foo { local_field: number; }";
        let module = crate::parser::parse_typescript(local_source).unwrap();
        let mut local_reg = crate::registry::build_registry(&module);
        // Merge external first, then local overwrites
        local_reg.merge(&external_reg);
        // Re-merge local on top (this is how transpile_with_registry works:
        // local reg merges shared, so local definitions win)
        let local_reg2 = crate::registry::build_registry(&module);
        local_reg.merge(&local_reg2);

        let foo = local_reg.get("Foo").unwrap();
        match foo {
            TypeDef::Struct { fields, .. } => {
                // Local definition should be present
                assert!(
                    fields.iter().any(|(name, _)| name == "local_field"),
                    "local definition should take precedence, got: {fields:?}"
                );
            }
            _ => panic!("expected Struct"),
        }
    }

    // ── Built-in types ─────────────────────────────────────────────

    #[test]
    fn test_load_builtin_types_succeeds() {
        let registry = load_builtin_types().unwrap();
        // Should contain key Web API types
        assert!(
            registry.get("Response").is_some(),
            "builtin types should contain Response"
        );
        assert!(
            registry.get("Request").is_some(),
            "builtin types should contain Request"
        );
        assert!(
            registry.get("Headers").is_some(),
            "builtin types should contain Headers"
        );
        assert!(
            registry.get("URL").is_some(),
            "builtin types should contain URL"
        );
    }

    #[test]
    fn test_builtin_response_has_status_field() {
        let registry = load_builtin_types().unwrap();
        let response = registry.get("Response").unwrap();
        match response {
            TypeDef::Struct { fields, .. } => {
                assert!(
                    fields.iter().any(|(name, _)| name == "status"),
                    "Response should have status field, got: {fields:?}"
                );
            }
            _ => panic!("Response should be a Struct"),
        }
    }

    #[test]
    fn test_builtin_response_has_inherited_body_methods() {
        let registry = load_builtin_types().unwrap();
        let response = registry.get("Response").unwrap();
        match response {
            TypeDef::Struct { methods, .. } => {
                assert!(
                    methods.contains_key("json"),
                    "Response should have json() from Body, got methods: {:?}",
                    methods.keys().collect::<Vec<_>>()
                );
                assert!(
                    methods.contains_key("text"),
                    "Response should have text() from Body, got methods: {:?}",
                    methods.keys().collect::<Vec<_>>()
                );
            }
            _ => panic!("Response should be a Struct"),
        }
    }

    #[test]
    fn test_builtin_headers_has_get_method() {
        let registry = load_builtin_types().unwrap();
        let headers = registry.get("Headers").unwrap();
        match headers {
            TypeDef::Struct { methods, .. } => {
                assert!(
                    methods.contains_key("get"),
                    "Headers should have get() method"
                );
                assert!(
                    methods.contains_key("set"),
                    "Headers should have set() method"
                );
                assert!(
                    methods.contains_key("append"),
                    "Headers should have append() method"
                );
            }
            _ => panic!("Headers should be a Struct"),
        }
    }
}
