use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{bail, Context, Result};
use clap::{Parser, Subcommand};

use ts_to_rs::directory;
use ts_to_rs::pipeline::module_resolver::NodeModuleResolver;
use ts_to_rs::pipeline::module_resolver::TrivialResolver;
use ts_to_rs::pipeline::output_writer::OutputWriter;
use ts_to_rs::pipeline::{OutputFile, TranspileInput};
use ts_to_rs::registry::TypeRegistry;
use ts_to_rs::UnsupportedSyntax;

/// TypeScript to Rust transpiler CLI tool.
#[derive(Parser, Debug)]
#[command(version, about = "Transpile TypeScript source code to Rust")]
struct Cli {
    #[command(subcommand)]
    command: Option<Commands>,

    /// Input TypeScript file or directory path
    input: Option<PathBuf>,

    /// Output Rust file or directory path (defaults to <input>.rs or <input>_rs/)
    #[arg(short, long)]
    output: Option<PathBuf>,

    /// Report unsupported syntax as JSON to stdout instead of aborting on errors
    #[arg(long)]
    report_unsupported: bool,

    /// Disable built-in Web API type definitions (Response, Request, Headers, etc.)
    #[arg(long)]
    no_builtin_types: bool,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Resolve external type definitions using the TypeScript compiler via Docker
    ResolveTypes {
        /// Path to tsconfig.json
        #[arg(long)]
        tsconfig: PathBuf,

        /// Output path for the resolved types JSON (default: .ts_to_rs/types.json)
        #[arg(short, long)]
        output: Option<PathBuf>,
    },
}

/// Docker image name for the type extraction tool.
const DOCKER_IMAGE: &str = "ts-to-rs-extract-types";

fn main() -> Result<()> {
    let cli = parse_cli();

    if let Some(command) = cli.command {
        return match command {
            Commands::ResolveTypes { tsconfig, output } => {
                resolve_types(&tsconfig, output.as_deref())
            }
        };
    }

    let input = cli
        .input
        .context("input path is required for transpilation")?;
    let use_builtin = !cli.no_builtin_types;

    if input.is_dir() {
        transpile_directory(
            &input,
            cli.output.as_deref(),
            use_builtin,
            cli.report_unsupported,
        )
    } else {
        transpile_file(
            &input,
            cli.output.as_deref(),
            use_builtin,
            cli.report_unsupported,
        )
    }
}

// ===== Transpilation =====

/// Transpiles a single TypeScript file to Rust using the unified pipeline.
fn transpile_file(
    input: &Path,
    output: Option<&Path>,
    use_builtin_types: bool,
    report_unsupported: bool,
) -> Result<()> {
    let ts_source = fs::read_to_string(input)
        .with_context(|| format!("failed to read input file: {}", input.display()))?;

    let input_dir = input.parent().unwrap_or(Path::new("."));
    let (builtin_types, base_synthetic) = build_base_registry(input_dir, use_builtin_types);

    let pipeline_input = TranspileInput {
        files: vec![(input.to_path_buf(), ts_source)],
        builtin_types: Some(builtin_types),
        base_synthetic: Some(base_synthetic),
        module_resolver: Box::new(TrivialResolver),
    };
    let pipeline_output = ts_to_rs::pipeline::transpile_pipeline(pipeline_input)
        .with_context(|| format!("failed to transpile: {}", input.display()))?;

    let ts_to_rs::pipeline::TranspileOutput {
        files,
        synthetic_items,
        ..
    } = pipeline_output;
    let mut file = files
        .into_iter()
        .next()
        .context("pipeline returned no output files")?;

    // Merge referenced synthetic items (marker structs, union enums) into file output.
    // Without this, callable interface marker structs generated by convert_callable_trait_const
    // would be missing from the CLI output (they live in synthetic_items, not file.rust_source).
    let prepended = ts_to_rs::pipeline::placement::render_referenced_synthetics_for_file(
        &file.path,
        &file.items,
        &synthetic_items,
    );
    if !prepended.is_empty() {
        file.rust_source = if file.rust_source.is_empty() {
            prepended
        } else {
            format!("{prepended}\n\n{}", file.rust_source)
        };
    }

    // Report or error on unsupported syntax
    if report_unsupported {
        let unsupported: Vec<UnsupportedSyntax> = file
            .unsupported
            .into_iter()
            .map(|raw| resolve_unsupported(&file.source, input, raw))
            .collect();
        let json = serde_json::to_string_pretty(&unsupported)?;
        println!("{json}");
    } else if let Some(first) = file.unsupported.first() {
        bail!(
            "unsupported syntax: {} at byte {} in {}",
            first.kind,
            first.byte_pos,
            input.display()
        );
    }

    let output_path = output
        .map(PathBuf::from)
        .unwrap_or_else(|| default_file_output_path(input));

    fs::write(&output_path, &file.rust_source)
        .with_context(|| format!("failed to write output file: {}", output_path.display()))?;

    ts_to_rs::run_rustfmt(std::slice::from_ref(&output_path));
    eprintln!("Wrote {}", output_path.display());
    Ok(())
}

/// Transpiles all `.ts` files in a directory using the unified pipeline + OutputWriter.
fn transpile_directory(
    input_dir: &Path,
    output: Option<&Path>,
    use_builtin_types: bool,
    report_unsupported: bool,
) -> Result<()> {
    let ts_files = directory::collect_ts_files(input_dir)?;
    directory::validate_has_ts_files(&ts_files, input_dir)?;

    let output_dir = output
        .map(PathBuf::from)
        .unwrap_or_else(|| default_directory_output_path(input_dir));

    // Read all source files
    let mut files: Vec<(PathBuf, String)> = Vec::new();
    for ts_path in &ts_files {
        let ts_source = fs::read_to_string(ts_path)
            .with_context(|| format!("failed to read: {}", ts_path.display()))?;
        files.push((ts_path.clone(), ts_source));
    }

    let (builtin_types, base_synthetic) = build_base_registry(input_dir, use_builtin_types);
    let known_files: HashSet<PathBuf> = ts_files.iter().cloned().collect();

    let pipeline_input = TranspileInput {
        files,
        builtin_types: Some(builtin_types),
        base_synthetic: Some(base_synthetic),
        module_resolver: Box::new(NodeModuleResolver::new(
            input_dir.to_path_buf(),
            known_files,
        )),
    };
    let pipeline_output = ts_to_rs::pipeline::transpile_pipeline(pipeline_input)
        .with_context(|| format!("failed to transpile directory: {}", input_dir.display()))?;

    // Collect unsupported syntax for reporting
    let mut all_unsupported = Vec::new();
    if report_unsupported {
        for file_output in &pipeline_output.files {
            let ts_path = file_output.path.with_extension("ts");
            for raw in &file_output.unsupported {
                all_unsupported.push(resolve_unsupported(
                    &file_output.source,
                    &ts_path,
                    raw.clone(),
                ));
            }
        }
    } else {
        // Strict mode: error on first unsupported
        for file_output in &pipeline_output.files {
            if let Some(first) = file_output.unsupported.first() {
                let ts_path = file_output.path.with_extension("ts");
                bail!(
                    "unsupported syntax: {} at byte {} in {}",
                    first.kind,
                    first.byte_pos,
                    ts_path.display()
                );
            }
        }
    }

    // Compute output paths: .ts → .rs, preserving directory structure
    // I-371: OutputFile に items を渡し、OutputWriter が IR ベースで配置を決定する
    let outputs: Vec<OutputFile<'_>> = pipeline_output
        .files
        .iter()
        .zip(ts_files.iter())
        .map(|(fo, ts_path)| {
            let rs_path = directory::compute_output_path(ts_path, input_dir, &output_dir)
                .unwrap_or_else(|_| ts_path.with_extension("rs"));
            // Use relative path within output_dir for OutputWriter
            let rel_path = rs_path
                .strip_prefix(&output_dir)
                .unwrap_or(&rs_path)
                .to_path_buf();
            OutputFile {
                rel_path,
                source: &fo.rust_source,
                items: &fo.items,
            }
        })
        .collect();

    // Write files + mod.rs + synthetic types via OutputWriter
    let writer = OutputWriter::new(&pipeline_output.module_graph);
    writer.write_to_directory(
        &output_dir,
        &outputs,
        &pipeline_output.synthetic_items,
        true, // run rustfmt
    )?;

    eprintln!("Converted {} file(s)", ts_files.len());

    if report_unsupported {
        let json = serde_json::to_string_pretty(&all_unsupported)?;
        println!("{json}");
    }

    Ok(())
}

// ===== Helpers =====

fn parse_cli() -> Cli {
    Cli::parse()
}

#[cfg(test)]
fn parse_cli_from<I, T>(iter: I) -> std::result::Result<Cli, clap::Error>
where
    I: IntoIterator<Item = T>,
    T: Into<std::ffi::OsString> + Clone,
{
    Cli::try_parse_from(iter)
}

fn default_file_output_path(input: &Path) -> PathBuf {
    input.with_extension("rs")
}

fn default_directory_output_path(input_dir: &Path) -> PathBuf {
    directory::default_output_dir(input_dir)
}

/// Resolves an [`UnsupportedSyntaxError`] into an [`UnsupportedSyntax`] with file path + line/col.
fn resolve_unsupported(
    source: &str,
    file_path: &Path,
    raw: ts_to_rs::transformer::UnsupportedSyntaxError,
) -> UnsupportedSyntax {
    let resolved = ts_to_rs::resolve_unsupported(source, raw);
    UnsupportedSyntax {
        kind: resolved.kind,
        location: format!("{}:{}", file_path.display(), resolved.location),
    }
}

/// Builds a base registry from built-in types and optional external types.json.
fn build_base_registry(
    input_dir: &Path,
    use_builtin_types: bool,
) -> (TypeRegistry, ts_to_rs::pipeline::SyntheticTypeRegistry) {
    let (mut registry, mut base_synthetic) = if use_builtin_types {
        ts_to_rs::external_types::load_builtin_types().unwrap_or_else(|_| {
            (
                TypeRegistry::new(),
                ts_to_rs::pipeline::SyntheticTypeRegistry::new(),
            )
        })
    } else {
        (
            TypeRegistry::new(),
            ts_to_rs::pipeline::SyntheticTypeRegistry::new(),
        )
    };

    // Auto-detect .ts_to_rs/types.json
    if let Some((external_reg, external_synthetic)) = load_external_types_json(input_dir) {
        registry.merge(&external_reg);
        base_synthetic.merge(external_synthetic);
    }

    (registry, base_synthetic)
}

/// Loads external types from `.ts_to_rs/types.json` if it exists in the input directory.
fn load_external_types_json(
    input_dir: &Path,
) -> Option<(TypeRegistry, ts_to_rs::pipeline::SyntheticTypeRegistry)> {
    let types_json = input_dir.join(".ts_to_rs/types.json");
    if !types_json.exists() {
        return None;
    }
    let json = fs::read_to_string(&types_json).ok()?;
    match ts_to_rs::external_types::load_types_json(&json) {
        Ok((reg, synthetic)) => {
            eprintln!("Loaded external types from {}", types_json.display());
            Some((reg, synthetic))
        }
        Err(e) => {
            eprintln!("Warning: failed to load {}: {e}", types_json.display());
            None
        }
    }
}

// ===== Docker / resolve-types =====

/// Resolves external type definitions by running tsc via Docker.
fn resolve_types(tsconfig: &Path, output: Option<&Path>) -> Result<()> {
    let tsconfig = tsconfig
        .canonicalize()
        .with_context(|| format!("tsconfig not found: {}", tsconfig.display()))?;
    let project_dir = tsconfig
        .parent()
        .context("tsconfig has no parent directory")?;

    let output_path = output
        .map(PathBuf::from)
        .unwrap_or_else(|| project_dir.join(".ts_to_rs/types.json"));

    // Ensure Docker is available
    let docker_check = Command::new("docker").arg("--version").output();
    match docker_check {
        Ok(o) if o.status.success() => {}
        Ok(_) => {
            bail!("Docker is installed but returned an error. Ensure Docker daemon is running.")
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            bail!(
                "Docker is not installed. Install Docker to use resolve-types.\n\
                 Alternatively, built-in Web API types are available without Docker."
            );
        }
        Err(e) => bail!("Failed to check Docker: {e}"),
    }

    // Check if image exists, build if not
    let image_check = Command::new("docker")
        .args(["image", "inspect", DOCKER_IMAGE])
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status();
    if !image_check.map(|s| s.success()).unwrap_or(false) {
        eprintln!("Building Docker image '{DOCKER_IMAGE}'...");
        let dockerfile_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tools/extract-types");
        let status = Command::new("docker")
            .args([
                "build",
                "-t",
                DOCKER_IMAGE,
                &dockerfile_dir.to_string_lossy(),
            ])
            .status()
            .context("failed to build Docker image")?;
        if !status.success() {
            bail!("Docker image build failed");
        }
    }

    // Run the extraction container
    eprintln!("Resolving types from {}...", tsconfig.display());
    let tsconfig_filename = tsconfig
        .file_name()
        .context("invalid tsconfig path")?
        .to_string_lossy();
    let output_docker = Command::new("docker")
        .args([
            "run",
            "--rm",
            "-v",
            &format!("{}:/project:ro", project_dir.display()),
            DOCKER_IMAGE,
            "--tsconfig",
            &format!("/project/{tsconfig_filename}"),
        ])
        .output()
        .context("failed to run Docker container")?;

    if !output_docker.status.success() {
        let stderr = String::from_utf8_lossy(&output_docker.stderr);
        bail!("Type extraction failed:\n{stderr}");
    }

    // Write output
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create directory: {}", parent.display()))?;
    }
    fs::write(&output_path, &output_docker.stdout)
        .with_context(|| format!("failed to write: {}", output_path.display()))?;

    eprintln!("Wrote {}", output_path.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn test_parse_cli_from_transpile_flags_and_input() {
        let cli = parse_cli_from([
            "ts_to_rs",
            "input.ts",
            "--output",
            "out.rs",
            "--report-unsupported",
            "--no-builtin-types",
        ])
        .expect("CLI args should parse");

        assert!(
            cli.command.is_none(),
            "plain transpile mode should have no subcommand"
        );
        assert_eq!(cli.input, Some(PathBuf::from("input.ts")));
        assert_eq!(cli.output, Some(PathBuf::from("out.rs")));
        assert!(cli.report_unsupported);
        assert!(cli.no_builtin_types);
    }

    #[test]
    fn test_parse_cli_from_resolve_types_subcommand_and_output() {
        let cli = parse_cli_from([
            "ts_to_rs",
            "resolve-types",
            "--tsconfig",
            "tsconfig.json",
            "--output",
            "types.json",
        ])
        .expect("resolve-types args should parse");

        match cli.command {
            Some(Commands::ResolveTypes { tsconfig, output }) => {
                assert_eq!(tsconfig, PathBuf::from("tsconfig.json"));
                assert_eq!(output, Some(PathBuf::from("types.json")));
            }
            other => panic!("expected resolve-types subcommand, got {other:?}"),
        }

        assert!(
            cli.input.is_none(),
            "subcommand form should not consume positional transpile input"
        );
    }

    #[test]
    fn test_parse_cli_from_rejects_unknown_resolve_types_option() {
        let err = parse_cli_from(["ts_to_rs", "resolve-types", "--bogus"])
            .expect_err("unknown resolve-types option should be rejected by clap");
        let msg = err.to_string();

        assert!(
            msg.contains("--bogus"),
            "unexpected clap diagnostic for unknown resolve-types option: {msg}"
        );
        assert!(
            msg.contains("resolve-types"),
            "diagnostic should stay scoped to the resolve-types subcommand: {msg}"
        );
    }

    #[test]
    fn test_parse_cli_from_rejects_resolve_types_missing_tsconfig_value() {
        let err = parse_cli_from(["ts_to_rs", "resolve-types", "--tsconfig"])
            .expect_err("missing tsconfig value should be rejected by clap");
        let msg = err.to_string();

        assert!(
            msg.contains("--tsconfig <TSCONFIG>"),
            "diagnostic should identify the missing tsconfig value: {msg}"
        );
        assert!(
            msg.contains("required"),
            "diagnostic should explain that the option requires a value: {msg}"
        );
    }

    #[test]
    fn test_default_file_output_path_replaces_extension_with_rs() {
        assert_eq!(
            default_file_output_path(Path::new("fixtures/example.input.ts")),
            PathBuf::from("fixtures/example.input.rs")
        );
    }

    #[test]
    fn test_default_directory_output_path_appends_rs_suffix() {
        assert_eq!(
            default_directory_output_path(Path::new("fixtures/src")),
            PathBuf::from("fixtures/src_rs")
        );
    }

    #[test]
    fn test_resolve_unsupported_prepends_file_path_and_line_col() {
        let source = "const ok = 1;\nexport default 42;\n";
        let raw = ts_to_rs::transformer::UnsupportedSyntaxError {
            kind: "ExportDefaultExpr".to_string(),
            byte_pos: 15,
        };

        let resolved = resolve_unsupported(source, Path::new("fixtures/demo.ts"), raw);

        assert_eq!(resolved.kind, "ExportDefaultExpr");
        assert_eq!(resolved.location, "fixtures/demo.ts:2:1");
    }
}
